import { Dungeon, Fish, GatherMaterial, MapData } from './map';

export const fishData: Record<string, Fish> = {
  prawns: { name: 'Prawns', bigIconUrl: 'fish_017_001' },
  tiger_crab: { name: 'Tiger Crab', bigIconUrl: 'fish_023_001' },
  mandarin_fish: { name: 'Mandarin Fish', bigIconUrl: 'fish_019_001' },
  jade_carp: { name: 'Jade Carp', bigIconUrl: 'fish_018_001' },
  twig_catfish: { name: 'Twig Catfish', bigIconUrl: 'fish_020_001' },
  jiujiang_mullet: { name: 'Jiujiang Mullet', bigIconUrl: 'fish_021_001' },
  speckled_perch: { name: 'Speckled Perch', bigIconUrl: 'fish_022_001' },
  red_bream: { name: 'Red Bream', bigIconUrl: 'fish_024_001', gold: true },
  pufferfish: { name: 'Pufferfish', bigIconUrl: 'fish_025_001', gold: true },
  sea_bass: { name: 'Sea Bass', bigIconUrl: 'fish_026_001', gold: true },
  exquisite_prawn: { name: 'Prawns', bigIconUrl: 'fish_017_002' },
  black_carp: { name: 'Black Carp', bigIconUrl: 'fish_027_001', gold: true }
};
export const materialData: Record<string, GatherMaterial> = {
  // student
  xihua_stone: { name: 'Xihua Stone', isGathering: true, bigIconUrl: 'hc_001', gold: true },
  white_obsidian: { name: 'White Obsidian', isGathering: true, bigIconUrl: 'hc_020', gold: true },
  cijin_stones: { name: 'Cijin Stones', isGathering: true, bigIconUrl: 'hc_019' },
  rattan_crystal: { name: 'Rattan Crystal', isGathering: true, bigIconUrl: 'hc_003', gold: true },
  tumbleweed: { name: 'Tumbleweed', isGathering: true, bigIconUrl: 'hc_004' },
  night_scent: { name: 'Night Scent', isGathering: true, bigIconUrl: 'hc_005', gold: true },
  thousand_leaf_pearls: { name: 'Thousand Leaf Pearls', isGathering: true, bigIconUrl: 'hc_017' },
  water_jade: { name: 'Water Jade', isGathering: true, bigIconUrl: 'hc_006' },
  ice_soul: { name: 'Ice Soul', isGathering: true, bigIconUrl: 'hc_015', gold: true },
  algal_crystal: { name: 'Algal Crystal', isGathering: true, bigIconUrl: 'hc_021' },
  fire_red_crystals: { name: 'Fire Red Crystals', isGathering: true, bigIconUrl: 'hc_007', gold: true },
  red_sand_crystal: { name: 'Red Sand Crystal', isGathering: true, bigIconUrl: 'hc_022' },
  inferno_stone: { name: 'Inferno Stone', isGathering: true, bigIconUrl: 'hc_024', gold: true },
  yellowstone: { name: 'Yellowstone', isGathering: true, bigIconUrl: 'hc_018' },
  dust_hearts: { name: 'Dust Hearts', isGathering: true, bigIconUrl: 'hc_009', gold: true },
  gold_bamboo_stones: { name: 'Gold Bamboo Stones', isGathering: true, bigIconUrl: 'hc_023' },
  earth_iris: { name: 'Earth Iris', isGathering: true, bigIconUrl: 'hc_025' },
  // sage
  gold_thread: { name: 'Gold Thread', isGathering: false, bigIconUrl: 'hc_002' },
  dragon_vertebra: { name: 'Dragon Vertebra', isGathering: true, bigIconUrl: 'hc_028' },
  star_bulrush: { name: 'Star Bulrush', isGathering: false, bigIconUrl: 'hc_029' },
  hexagonal_snowflake: { name: 'Hexagonal Snowflake', isGathering: false, bigIconUrl: 'hc_014' },
  ice_moss_clam: { name: 'Ice Moss Clam', isGathering: true, bigIconUrl: 'hc_026', gold: true },
  fire_pearl: { name: 'Fire Pearl', isGathering: false, bigIconUrl: 'hc_012' },
  ash_grass: { name: 'Ash Grass', isGathering: true, bigIconUrl: 'hc_027', gold: true },
  earth_sprite_hair: { name: 'Earth Sprite Hair', isGathering: false, bigIconUrl: 'hc_010' },
  stone_bolete: { name: 'Stone Bolete', isGathering: false, bigIconUrl: 'hc_030' },
  fertility_stone: { name: 'Fertility Stone', isGathering: true, bigIconUrl: 'hc_031' },
  // 3.0
  blue_moss_stone: { name: 'Blue Moss Stone', isGathering: true, bigIconUrl: 'hc_044' }
};
export const dungeonData: Record<string, Dungeon> = {
  // student
  yemo_city_in_wuzhao: { name: 'Yemo City in Wuzhao', playerCountMin: 5, playerCountMax: 10 },
  nightmare_temple_of_mercy: { name: 'Nightmare Temple of Mercy', playerCountMin: 5, playerCountMax: 10 },
  frostbitten_path: { name: 'Frostbitten Path', playerCountMin: 5, playerCountMax: 10 },
  chou_prison: { name: 'Chou Prison', playerCountMin: 5, playerCountMax: 10 },
  raging_river_ruins: { name: 'Raging River Ruins', playerCountMin: 5, playerCountMax: 10 },
  xuanjiu_jade_palace: { name: 'Xuanjiu Jade Palace', playerCountMin: 10, playerCountMax: 20 },
  waves_in_a_tempest: { name: 'Waves in a Tempest', playerCountMin: 10, playerCountMax: 20 },
  horror_of_huaixiu: { name: 'Horror of Huaixiu', playerCountMin: 10, playerCountMax: 20 },
  ruins_of_nuowu: { name: 'Ruins of Nuowu', playerCountMin: 10, playerCountMax: 20 },
  ice_world: { name: 'Ice World', playerCountMin: 10, playerCountMax: 20 },
  forbidden_court_in_the_floral_palace: { name: 'Forbidden Court in the Floral Palace', playerCountMin: 10, playerCountMax: 20 },
  sparkwood_gardens: { name: 'Sparkwood Gardens', playerCountMin: 10, playerCountMax: 20 },
  // sage
  rotting_grotto: { name: 'Rotting Grotto', playerCountMin: 5, playerCountMax: 10 },
  heavenly_gate_labyrinth: { name: 'Heavenly Gate Labyrinth', playerCountMin: 5, playerCountMax: 10 },
  firestone_grave_of_dreams: { name: 'Firestone Grave of Dreams', playerCountMin: 5, playerCountMax: 10 },
};
export const mapData: Array<MapData> = [
  { id: 's26', displayName: 'Baxian Plateau', worldIconUrl: 'baxian_plateau', showMapName: true,
    subMaps: ['Baxian Plateau', 'Cloudtop', 'Goldstar Cave'],
    worldIconPosition: { top: 30.6, left: 30.25, width: 12.8, height: 5.4 },
    dungeons: [dungeonData.ice_world],
    collectables: [],
    materials: [
      materialData.xihua_stone,
      materialData.water_jade,
      materialData.ice_soul
    ],
    fish: [fishData.twig_catfish, fishData.speckled_perch] },
  { id: 'm62', displayName: 'Changfu Garden', worldIconUrl: 'changfu_garden', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 26.5, left: 76, width: 13.1, height: 7.7 },
    dungeons: [dungeonData.rotting_grotto],
    collectables: [],
    materials: [
      materialData.night_scent,
      materialData.dragon_vertebra,
      materialData.ice_moss_clam,
      materialData.blue_moss_stone,
      materialData.gold_thread,
      materialData.star_bulrush,
      materialData.hexagonal_snowflake,
      materialData.fire_pearl,
      materialData.earth_sprite_hair,
      materialData.stone_bolete
    ],
    fish: [] },
  { id: 'm56', displayName: 'Changhe Mountain', worldIconUrl: 'changhe_mountain', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 77.7, left: 62.9, width: 12.3, height: 9.3 },
    dungeons: [dungeonData.firestone_grave_of_dreams],
    collectables: [],
    materials: [
      materialData.white_obsidian,
      materialData.ash_grass,
      materialData.fertility_stone,
      materialData.gold_thread,
      materialData.star_bulrush,
      materialData.hexagonal_snowflake,
      materialData.fire_pearl,
      materialData.earth_sprite_hair,
      materialData.stone_bolete
    ],
    fish: [] },
  { id: 'd47', displayName: 'Langquan Bridge', worldIconUrl: 'chanquan_bridge_cloudy', showMapName: true,
    subMaps: ['Langquan Empire Border Wall', 'Cloudless Bridge'],
    worldIconPosition: { top: 66.9, left: 73.8, width: 9.8, height: 8.2 },
    dungeons: [],
    collectables: [],
    materials: [
      materialData.gold_thread,
      materialData.star_bulrush,
      materialData.hexagonal_snowflake,
      materialData.fire_pearl,
      materialData.earth_sprite_hair,
      materialData.stone_bolete
    ],
    fish: [] },
  { id: 'm35', displayName: 'Cloudrise', worldIconUrl: 'cloudrise', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 14, left: 59.5, width: 13, height: 9.5 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'm33', displayName: 'District of Changan', worldIconUrl: 'district_of_changan', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 19.5, left: 40.5, width: 14.6, height: 7.7 },
    dungeons: [dungeonData.nightmare_temple_of_mercy],
    collectables: [],
    materials: [],
    fish: [fishData.prawns, fishData.mandarin_fish, fishData.jade_carp, fishData.sea_bass, fishData.exquisite_prawn] },
  { id: 'm34', displayName: 'District of Jiangdu', worldIconUrl: 'district_of_jiangdu', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 38.5, left: 75.7, width: 12, height: 7.2 },
    dungeons: [dungeonData.chou_prison],
    collectables: [],
    materials: [],
    fish: [
      fishData.prawns,
      fishData.tiger_crab,
      fishData.twig_catfish,
      fishData.jiujiang_mullet,
      fishData.speckled_perch,
      fishData.red_bream,
      fishData.pufferfish,
      fishData.black_carp
    ] },
  { id: 'm100', displayName: 'Dragonstar Dist.', worldIconUrl: 'dragonstar_district', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 54.5, left: 88, width: 15.5, height: 10.7 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 's34', displayName: 'Fifty Islands of Chuyun', worldIconUrl: 'fifty_islands_of_chuyun', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 6, left: 70.7, width: 12.6, height: 9 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'm60', displayName: 'Floral Palace', worldIconUrl: 'floral_palace', showMapName: true,
    subMaps: ['Floral Palace', 'Underground Palace'],
    worldIconPosition: { top: 58.2, left: 63.3, width: 13.6, height: 7.7 },
    dungeons: [dungeonData.sparkwood_gardens, dungeonData.forbidden_court_in_the_floral_palace],
    collectables: [],
    materials: [
      materialData.inferno_stone,
      materialData.white_obsidian,
      materialData.ice_moss_clam
    ],
    fish: [fishData.red_bream, fishData.twig_catfish, fishData.pufferfish, fishData.jiujiang_mullet, fishData.black_carp] },
  { id: 'm14', displayName: 'Heavenly Ridge', worldIconUrl: 'heavenly_ridge', showMapName: true,
    subMaps: ['Heavenly Ridge', 'Hall of Silence'],
    worldIconPosition: { top: 50.2, left: 22, width: 10.5, height: 9 },
    dungeons: [dungeonData.yemo_city_in_wuzhao],
    collectables: [],
    materials: [],
    fish: [fishData.mandarin_fish, fishData.jade_carp] },
  { id: 's21', displayName: 'Huaixiu Village', worldIconUrl: 'huaixiu_village', showMapName: true,
    subMaps: ['Huaixiu Village', 'Under the Well'],
    worldIconPosition: { top: 35, left: 49.4, width: 11.3, height: 6.8 },
    dungeons: [dungeonData.horror_of_huaixiu],
    collectables: [],
    materials: [
      materialData.cijin_stones,
      materialData.night_scent,
      materialData.hexagonal_snowflake,
      materialData.fire_red_crystals
    ],
    fish: [] },
  { id: 'm01', displayName: 'Realm of Light', worldIconUrl: 'realm_of_light', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 40.7, left: 89.4, width: 12.2, height: 9 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'm59', displayName: 'Shanghuai Grassland', worldIconUrl: 'shanghuai_grassland', showMapName: true,
    subMaps: ['Shanghuai Grassland', 'Zhan Family Sewer Tunnel', 'Jijia Village Underground Camp'],
    worldIconPosition: { top: 48.7, left: 69, width: 13.75, height: 7.7 },
    dungeons: [dungeonData.raging_river_ruins, dungeonData.waves_in_a_tempest, dungeonData.ruins_of_nuowu],
    collectables: [],
    materials: [
      materialData.rattan_crystal,
      materialData.night_scent,
      materialData.algal_crystal,
      materialData.red_sand_crystal,
      materialData.yellowstone,
      materialData.dust_hearts
    ],
    fish: [
      fishData.prawns,
      fishData.twig_catfish,
      fishData.jiujiang_mullet,
      fishData.red_bream,
      fishData.pufferfish,
      fishData.sea_bass,
      fishData.exquisite_prawn,
      fishData.black_carp
    ] },
  { id: 'm66', displayName: 'Taihua Mountain', worldIconUrl: 'taihua_mountain', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 6.4, left: 52.2, width: 11, height: 11.4 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'b06', displayName: 'Valley of Echoing Blades', worldIconUrl: 'valley_of_echoing_blades', showMapName: true,
    subMaps: ['Valley of Echoing Blades', 'Old Crane Passage', 'Remains of the Kuying Path'],
    worldIconPosition: { top: 28.6, left: 59.4, width: 13.2, height: 7.6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'm13', displayName: 'Valley of a Hundred Grasses', worldIconUrl: 'way_of_a_hundred_grasses', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 68, left: 52.4, width: 12.5, height: 6.6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'm58', displayName: 'Weichuan Highlands', worldIconUrl: 'weichuan_highlands', showMapName: true,
    subMaps: ['Weichuan Highlands', 'Wood of Veracity Grotto'],
    worldIconPosition: { top: 23.2, left: 49.3, width: 11.8, height: 6.3 },
    dungeons: [dungeonData.frostbitten_path],
    collectables: [],
    materials: [materialData.rattan_crystal, materialData.tumbleweed, materialData.dust_hearts],
    fish: [fishData.tiger_crab, fishData.mandarin_fish, fishData.jade_carp, fishData.sea_bass, fishData.exquisite_prawn] },
  { id: 'm45', displayName: 'Wild Wolf Plateau', worldIconUrl: 'wild_wolf_plateau', showMapName: true,
    subMaps: [],
    worldIconPosition: { top: 11.3, left: 32.5, width: 13.1, height: 10 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'm57', displayName: 'Zhongnan Foothills', worldIconUrl: 'zhongnan_foothills', showMapName: true,
    subMaps: ['Zhongnan Foothills', 'Shanyoulin Grotto', 'Squall Shipping Co. Storeroom'],
    worldIconPosition: { top: 40.2, left: 38.3, width: 11.1, height: 9.25 },
    dungeons: [dungeonData.xuanjiu_jade_palace],
    collectables: [],
    materials: [
      materialData.xihua_stone,
      materialData.thousand_leaf_pearls,
      materialData.ice_soul,
      materialData.fire_red_crystals,
      materialData.gold_bamboo_stones,
      materialData.earth_iris
    ],
    fish: [
      fishData.tiger_crab,
      fishData.mandarin_fish,
      fishData.jade_carp,
      fishData.speckled_perch,
      fishData.red_bream,
      fishData.pufferfish,
      fishData.black_carp
    ] },
  { id: 'BTL', displayName: 'Sea of Flowers', worldIconUrl: 'BTL', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 49, left: 29.5, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'CXXZ', displayName: 'Chixia\'s House', worldIconUrl: 'CXXZ', showMapName: false,
    subMaps: ['Chixia\'s House', 'Taihua Mountain Path', 'Stygian Path', 'Qin Mausoleum Ruins', 'Plateau of Valorous Steel'],
    worldIconPosition: { top: 7.5, left: 51.8, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'GYBZY', displayName: 'Luan Crown Institute', worldIconUrl: 'GYBZY', showMapName: false,
    subMaps: ['Valley of a Hundred Grasses', 'Luan Crown Institute'],
    worldIconPosition: { top: 68.3, left: 52, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'HSYJ', displayName: 'Ruins of Nuowu', worldIconUrl: 'HSYJ', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 50, left: 78.5, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'JLT', displayName: 'Dreamworld of the Nine Dragon Mere', worldIconUrl: 'JLT', showMapName: false,
    subMaps: ['Fire Dreamworld', 'Metal Dreamworld', 'Blackwater Dreamworld', 'Shattered Wood Dreamworld', 'Earth Dreamworld'],
    worldIconPosition: { top: 50, left: 41.8, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'LHT', displayName: 'Snowing Blossom Paradise', worldIconUrl: 'LHT', showMapName: false,
    subMaps: ['Snowing Blossom Paradise', 'Orchid Marsh', 'Fangwu Island'],
    worldIconPosition: { top: 59, left: 63, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [materialData.fertility_stone],
    fish: [] },
  { id: 'TMS', displayName: 'Tianmu Plain', worldIconUrl: 'TMS', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 79, left: 71.3, width: 4, height: 6 },
    dungeons: [dungeonData.heavenly_gate_labyrinth],
    collectables: [],
    materials: [
      materialData.white_obsidian,
      materialData.ash_grass,
      materialData.fertility_stone
    ],
    fish: [] },
  { id: 'THS', displayName: 'Blade Peak', worldIconUrl: 'THS', showMapName: false,
    subMaps: ['Taihua Mountain Path Lower Level', 'Taihua Mountain Path Upper Level', 'Red Dawn Podium', 'Sword Sanctum Dreamworld'],
    worldIconPosition: { top: 13.5, left: 51.8, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'TG', displayName: 'Star Tempest', worldIconUrl: 'TG', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 15, left: 67.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'LHT', displayName: 'Snowing Blossom Paradise', worldIconUrl: 'LY', showMapName: false,
    subMaps: ['Snowing Blossom Paradise', 'Orchid Marsh', 'Fangwu Island'],
    worldIconPosition: { top: 18, left: 67.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [materialData.fertility_stone],
    fish: [] },
  { id: 'ZY', displayName: 'Chasm of Remote Darkness', worldIconUrl: 'ZY', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 21, left: 67.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'SM', displayName: 'Valley of the Sea of Fragrant Flowers', worldIconUrl: 'SM', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 13.5, left: 69, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'YJ', displayName: 'Sunken Jade Lake', worldIconUrl: 'YJ', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 16.5, left: 69, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'ZX', displayName: 'Holy Valley', worldIconUrl: 'ZX', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 19.5, left: 69, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'MF', displayName: 'Mountain of Wondrous Creation', worldIconUrl: 'MF', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 15, left: 70.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'LHT', displayName: 'Snowing Blossom Paradise', worldIconUrl: 'YF', showMapName: false,
    subMaps: ['Snowing Blossom Paradise', 'Orchid Marsh', 'Fangwu Island'],
    worldIconPosition: { top: 18, left: 70.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [materialData.fertility_stone],
    fish: [] },
  { id: 'ZF', displayName: 'Beautiful Rapture Quarter', worldIconUrl: 'ZF', showMapName: false,
    subMaps: ['Beautiful Rapture Quarter', 'Cerulean Cliff Terrace'],
    worldIconPosition: { top: 21, left: 70.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] }
];
export const mapDataExtra: Array<MapData> = [
  { id: 'BTL', displayName: 'Sea of Flowers', worldIconUrl: 'BTL', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 49, left: 29.5, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'CXXZ', displayName: 'Chixia\'s House', worldIconUrl: 'CXXZ', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 7.5, left: 51.8, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'GYBZY', displayName: 'Luan Crown Institute', worldIconUrl: 'GYBZY', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 68.3, left: 52, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'HSYJ', displayName: 'Ruins of Nuowu', worldIconUrl: 'HSYJ', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 50, left: 78.5, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'JLT', displayName: 'Dreamworld of the Nine Dragon Mere', worldIconUrl: 'JLT', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 50, left: 41.8, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'LHT', displayName: 'Snowing Blossom Paradise', worldIconUrl: 'LHT', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 59, left: 63, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'TMS', displayName: 'Tianmu Plain', worldIconUrl: 'TMS', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 79, left: 71.3, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'THS', displayName: 'Blade Peak', worldIconUrl: 'THS', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 13.5, left: 51.8, width: 4, height: 6 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'TG', displayName: 'Star Tempest', worldIconUrl: 'TG', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 15, left: 67.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'LHT', displayName: 'Snowing Blossom Paradise', worldIconUrl: 'LY', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 18, left: 67.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'ZY', displayName: 'Chasm of Remote Darkness', worldIconUrl: 'ZY', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 21, left: 67.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'SM', displayName: 'Valley of the Sea of Fragrant Flowers', worldIconUrl: 'SM', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 13.5, left: 69, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'YJ', displayName: 'Sunken Jade Lake', worldIconUrl: 'YJ', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 16.5, left: 69, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'ZX', displayName: 'Holy Valley', worldIconUrl: 'ZX', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 19.5, left: 69, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'MF', displayName: 'Mountain of Wondrous Creation', worldIconUrl: 'MF', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 15, left: 70.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'LHT', displayName: 'Snowing Blossom Paradise', worldIconUrl: 'YF', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 18, left: 70.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] },
  { id: 'ZF', displayName: 'Beautiful Rapture Quarter', worldIconUrl: 'ZF', showMapName: false,
    subMaps: [],
    worldIconPosition: { top: 21, left: 70.5, width: 1.7, height: 3 },
    dungeons: [],
    collectables: [],
    materials: [],
    fish: [] }
];
